// Generated by CoffeeScript 1.12.7
(function() {
  var BaseRenderer, Common2dRenderer, PI, PIXEL_SIZE_WORLD, TEAM_COLORS, TILE_SIZE_PIXELS, cos, distance, heading, min, ref, ref1, round, sin,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  min = Math.min, round = Math.round, PI = Math.PI, sin = Math.sin, cos = Math.cos;

  ref = require('../../constants'), TILE_SIZE_PIXELS = ref.TILE_SIZE_PIXELS, PIXEL_SIZE_WORLD = ref.PIXEL_SIZE_WORLD;

  ref1 = require('../../helpers'), distance = ref1.distance, heading = ref1.heading;

  BaseRenderer = require('./base');

  TEAM_COLORS = require('../../team_colors');

  Common2dRenderer = (function(superClass) {
    extend(Common2dRenderer, superClass);

    function Common2dRenderer() {
      return Common2dRenderer.__super__.constructor.apply(this, arguments);
    }

    Common2dRenderer.prototype.setup = function() {
      var ctx, e, imageData, img, temp;
      try {
        this.ctx = this.canvas[0].getContext('2d');
        this.ctx.drawImage;
      } catch (error) {
        e = error;
        throw "Could not initialize 2D canvas: " + e.message;
      }
      img = this.images.overlay;
      temp = $('<canvas/>')[0];
      temp.width = img.width;
      temp.height = img.height;
      ctx = temp.getContext('2d');
      ctx.globalCompositeOperation = 'copy';
      ctx.drawImage(img, 0, 0);
      imageData = ctx.getImageData(0, 0, img.width, img.height);
      this.overlay = imageData.data;
      return this.prestyled = {};
    };

    Common2dRenderer.prototype.drawTile = function(tx, ty, dx, dy, ctx) {
      return (ctx || this.ctx).drawImage(this.images.base, tx * TILE_SIZE_PIXELS, ty * TILE_SIZE_PIXELS, TILE_SIZE_PIXELS, TILE_SIZE_PIXELS, dx, dy, TILE_SIZE_PIXELS, TILE_SIZE_PIXELS);
    };

    Common2dRenderer.prototype.createPrestyled = function(color) {
      var base, ctx, data, factor, height, i, imageData, j, k, ref2, ref3, source, width, x, y;
      base = this.images.styled;
      width = base.width, height = base.height;
      source = $('<canvas/>')[0];
      source.width = width;
      source.height = height;
      ctx = source.getContext('2d');
      ctx.globalCompositeOperation = 'copy';
      ctx.drawImage(base, 0, 0);
      imageData = ctx.getImageData(0, 0, width, height);
      data = imageData.data;
      for (x = j = 0, ref2 = width; 0 <= ref2 ? j < ref2 : j > ref2; x = 0 <= ref2 ? ++j : --j) {
        for (y = k = 0, ref3 = height; 0 <= ref3 ? k < ref3 : k > ref3; y = 0 <= ref3 ? ++k : --k) {
          i = 4 * (y * width + x);
          factor = this.overlay[i] / 255;
          data[i + 0] = round(factor * color.r + (1 - factor) * data[i + 0]);
          data[i + 1] = round(factor * color.g + (1 - factor) * data[i + 1]);
          data[i + 2] = round(factor * color.b + (1 - factor) * data[i + 2]);
          data[i + 3] = min(255, data[i + 3] + this.overlay[i]);
        }
      }
      ctx.putImageData(imageData, 0, 0);
      return source;
    };

    Common2dRenderer.prototype.drawStyledTile = function(tx, ty, style, dx, dy, ctx) {
      var color, source;
      if (!(source = this.prestyled[style])) {
        source = (color = TEAM_COLORS[style]) ? this.prestyled[style] = this.createPrestyled(color) : this.images.styled;
      }
      return (ctx || this.ctx).drawImage(source, tx * TILE_SIZE_PIXELS, ty * TILE_SIZE_PIXELS, TILE_SIZE_PIXELS, TILE_SIZE_PIXELS, dx, dy, TILE_SIZE_PIXELS, TILE_SIZE_PIXELS);
    };

    Common2dRenderer.prototype.centerOn = function(x, y, cb) {
      var height, left, ref2, top, width;
      this.ctx.save();
      ref2 = this.getViewAreaAtWorld(x, y), left = ref2[0], top = ref2[1], width = ref2[2], height = ref2[3];
      this.ctx.translate(-left, -top);
      cb(left, top, width, height);
      return this.ctx.restore();
    };

    Common2dRenderer.prototype.drawBuilderIndicator = function(b) {
      var dist, offset, player, px, py, rad, x, y;
      player = b.owner.$;
      if ((dist = distance(player, b)) <= 128) {
        return;
      }
      px = player.x / PIXEL_SIZE_WORLD;
      py = player.y / PIXEL_SIZE_WORLD;
      this.ctx.save();
      this.ctx.globalCompositeOperation = 'source-over';
      this.ctx.globalAlpha = min(1.0, (dist - 128) / 1024);
      offset = min(50, dist / 10240 * 50) + 32;
      rad = heading(player, b);
      this.ctx.beginPath();
      this.ctx.moveTo(x = px + cos(rad) * offset, y = py + sin(rad) * offset);
      rad += PI;
      this.ctx.lineTo(x + cos(rad - 0.4) * 10, y + sin(rad - 0.4) * 10);
      this.ctx.lineTo(x + cos(rad + 0.4) * 10, y + sin(rad + 0.4) * 10);
      this.ctx.closePath();
      this.ctx.fillStyle = 'yellow';
      this.ctx.fill();
      return this.ctx.restore();
    };

    Common2dRenderer.prototype.drawNames = function() {
      var dist, j, len, metrics, player, ref2, tank, x, y;
      this.ctx.save();
      this.ctx.strokeStyle = this.ctx.fillStyle = 'white';
      this.ctx.font = 'bold 11px sans-serif';
      this.ctx.textBaselines = 'alphabetic';
      this.ctx.textAlign = 'left';
      player = this.world.player;
      ref2 = this.world.tanks;
      for (j = 0, len = ref2.length; j < len; j++) {
        tank = ref2[j];
        if (!(tank.name && tank.armour !== 255 && tank !== player)) {
          continue;
        }
        if (player) {
          if ((dist = distance(player, tank)) <= 768) {
            continue;
          }
          this.ctx.globalAlpha = min(1.0, (dist - 768) / 1536);
        } else {
          this.ctx.globalAlpha = 1.0;
        }
        metrics = this.ctx.measureText(tank.name);
        this.ctx.beginPath();
        this.ctx.moveTo(x = round(tank.x / PIXEL_SIZE_WORLD) + 16, y = round(tank.y / PIXEL_SIZE_WORLD) - 16);
        this.ctx.lineTo(x += 12, y -= 9);
        this.ctx.lineTo(x + metrics.width, y);
        this.ctx.stroke();
        this.ctx.fillText(tank.name, x, y - 2);
      }
      return this.ctx.restore();
    };

    return Common2dRenderer;

  })(BaseRenderer);

  module.exports = Common2dRenderer;

}).call(this);
