// Generated by CoffeeScript 1.12.7
(function() {
  var MapIndex, fs, path;

  fs = require('fs');

  path = require('path');

  MapIndex = (function() {
    function MapIndex(mapPath, callback) {
      this.mapPath = mapPath;
      this.reindex(callback);
    }

    MapIndex.prototype.reindex = function(callback) {
      var fuzzy, index, names;
      this.nameIndex = names = {};
      this.fuzzyIndex = fuzzy = {};
      index = function(file, callback) {
        return fs.stat(file, function(err, stats) {
          var descr, m;
          if (err) {
            console.log(err.toString());
            return typeof callback === "function" ? callback() : void 0;
          }
          if (stats.isDirectory()) {
            return fs.readdir(file, function(err, subfiles) {
              var counter, i, len, results1, subfile;
              if (err) {
                console.log(err.toString());
                return typeof callback === "function" ? callback() : void 0;
              }
              counter = subfiles.length;
              results1 = [];
              for (i = 0, len = subfiles.length; i < len; i++) {
                subfile = subfiles[i];
                results1.push(index(path.join(file, subfile), function() {
                  if (--counter === 0) {
                    return typeof callback === "function" ? callback() : void 0;
                  }
                }));
              }
              return results1;
            });
          } else if (m = /([^\/]+?)\.map$/i.exec(file)) {
            descr = {
              name: m[1],
              path: file
            };
            names[descr.name] = fuzzy[descr.name.replace(/[\W_]+/g, '')] = descr;
            return typeof callback === "function" ? callback() : void 0;
          } else {
            return typeof callback === "function" ? callback() : void 0;
          }
        });
      };
      index(this.mapPath, callback);
    };

    MapIndex.prototype.get = function(name) {
      return this.nameIndex[name];
    };

    MapIndex.prototype.fuzzy = function(s) {
      var descr, fuzzed, input, matcher, ref, results;
      input = s.replace(/[\W_]+/g, '');
      matcher = new RegExp(input, 'i');
      results = [];
      ref = this.fuzzyIndex;
      for (fuzzed in ref) {
        descr = ref[fuzzed];
        if (fuzzed === input) {
          return [descr];
        } else if (matcher.test(fuzzed)) {
          results.push(descr);
        }
      }
      return results;
    };

    return MapIndex;

  })();

  module.exports = MapIndex;

}).call(this);
