// Generated by CoffeeScript 1.12.7
(function() {
  var BoloLocalWorld, BoloNetworkWorld;

  BoloLocalWorld = require('./world/local');

  BoloNetworkWorld = require('./world/client');

  if (location.search === '?local') {
    module.exports = BoloLocalWorld;
  } else {
    module.exports = BoloNetworkWorld;
  }

}).call(this);
