// Generated by CoffeeScript 1.12.7
(function() {
  var BoloClientWorld, ClientWorld, JOIN_DIALOG_TEMPLATE, WorldBase, WorldMap, WorldPillbox, allObjects, decodeBase64, helpers, net, unpack,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  ClientWorld = require('villain/world/net/client');

  WorldMap = require('../../world_map');

  allObjects = require('../../objects/all');

  WorldPillbox = require('../../objects/world_pillbox');

  WorldBase = require('../../objects/world_base');

  unpack = require('../../struct').unpack;

  decodeBase64 = require('../base64').decodeBase64;

  net = require('../../net');

  helpers = require('../../helpers');

  JOIN_DIALOG_TEMPLATE = "<div id=\"join-dialog\">\n  <div>\n    <p>What is your name?</p>\n    <p><input type=\"text\" id=\"join-nick-field\" name=\"join-nick-field\" maxlength=20></input></p>\n  </div>\n  <div id=\"join-team\">\n    <p>Choose a side:</p>\n    <p>\n      <input type=\"radio\" id=\"join-team-red\" name=\"join-team\" value=\"red\"></input>\n      <label for=\"join-team-red\"><span class=\"bolo-team bolo-team-red\"></span></label>\n      <input type=\"radio\" id=\"join-team-blue\" name=\"join-team\" value=\"blue\"></input>\n      <label for=\"join-team-blue\"><span class=\"bolo-team bolo-team-blue\"></span></label>\n    </p>\n  </div>\n  <div>\n    <p><input type=\"button\" name=\"join-submit\" id=\"join-submit\" value=\"Join game\"></input></p>\n  </div>\n</div>";

  BoloClientWorld = (function(superClass) {
    extend(BoloClientWorld, superClass);

    BoloClientWorld.prototype.authority = false;

    function BoloClientWorld() {
      BoloClientWorld.__super__.constructor.apply(this, arguments);
      this.mapChanges = {};
      this.processingServerMessages = false;
    }

    BoloClientWorld.prototype.loaded = function(vignette) {
      var m, path, protocol, ws;
      this.vignette = vignette;
      this.vignette.message('Connecting to the multiplayer game');
      this.heartbeatTimer = 0;
      if (m = /^\?([a-z]{20})$/.exec(location.search)) {
        path = "/match/" + m[1];
      } else if (location.search) {
        return this.vignette.message('Invalid game ID');
      } else {
        path = "/demo";
      }
      protocol = location.protocol === 'https:' ? 'wss:' : 'ws:';
      this.ws = new WebSocket(protocol + "//" + location.host + path);
      ws = $(this.ws);
      ws.one('open.bolo', (function(_this) {
        return function() {
          return _this.connected();
        };
      })(this));
      return ws.one('close.bolo', (function(_this) {
        return function() {
          return _this.failure('Connection lost');
        };
      })(this));
    };

    BoloClientWorld.prototype.connected = function() {
      var ws;
      this.vignette.message('Waiting for the game map');
      ws = $(this.ws);
      return ws.one('message.bolo', (function(_this) {
        return function(e) {
          return _this.receiveMap(e.originalEvent);
        };
      })(this));
    };

    BoloClientWorld.prototype.receiveMap = function(e) {
      this.map = WorldMap.load(decodeBase64(e.data));
      this.commonInitialization();
      this.vignette.message('Waiting for the game state');
      return $(this.ws).bind('message.bolo', (function(_this) {
        return function(e) {
          return _this.handleMessage(e.originalEvent);
        };
      })(this));
    };

    BoloClientWorld.prototype.synchronized = function() {
      var blue, disadvantaged, i, len, red, ref, tank;
      this.rebuildMapObjects();
      this.vignette.destroy();
      this.vignette = null;
      this.loop.start();
      red = blue = 0;
      ref = this.tanks;
      for (i = 0, len = ref.length; i < len; i++) {
        tank = ref[i];
        if (tank.team === 0) {
          red++;
        }
        if (tank.team === 1) {
          blue++;
        }
      }
      disadvantaged = blue < red ? 'blue' : 'red';
      this.joinDialog = $(JOIN_DIALOG_TEMPLATE).dialog({
        dialogClass: 'unclosable'
      });
      return this.joinDialog.find('#join-nick-field').val($.cookie('nick') || '').focus().keydown((function(_this) {
        return function(e) {
          if (e.which === 13) {
            return _this.join();
          }
        };
      })(this)).end().find("#join-team-" + disadvantaged).attr('checked', 'checked').end().find("#join-team").buttonset().end().find('#join-submit').button().click((function(_this) {
        return function() {
          return _this.join();
        };
      })(this));
    };

    BoloClientWorld.prototype.join = function() {
      var nick, team;
      nick = this.joinDialog.find('#join-nick-field').val();
      team = this.joinDialog.find('#join-team input[checked]').val();
      team = (function() {
        switch (team) {
          case 'red':
            return 0;
          case 'blue':
            return 1;
          default:
            return -1;
        }
      })();
      if (!(nick && team !== -1)) {
        return;
      }
      $.cookie('nick', nick);
      this.joinDialog.dialog('destroy');
      this.joinDialog = null;
      this.ws.send(JSON.stringify({
        command: 'join',
        nick: nick,
        team: team
      }));
      return this.input.focus();
    };

    BoloClientWorld.prototype.receiveWelcome = function(tank) {
      this.player = tank;
      this.renderer.initHud();
      return this.initChat();
    };

    BoloClientWorld.prototype.tick = function() {
      BoloClientWorld.__super__.tick.apply(this, arguments);
      if (this.increasingRange !== this.decreasingRange) {
        if (++this.rangeAdjustTimer === 6) {
          if (this.increasingRange) {
            this.ws.send(net.INC_RANGE);
          } else {
            this.ws.send(net.DEC_RANGE);
          }
          this.rangeAdjustTimer = 0;
        }
      } else {
        this.rangeAdjustTimer = 0;
      }
      if (++this.heartbeatTimer === 10) {
        this.heartbeatTimer = 0;
        return this.ws.send('');
      }
    };

    BoloClientWorld.prototype.failure = function(message) {
      if (this.ws) {
        this.ws.close();
        $(this.ws).unbind('.bolo');
        this.ws = null;
      }
      return BoloClientWorld.__super__.failure.apply(this, arguments);
    };

    BoloClientWorld.prototype.soundEffect = function(sfx, x, y, owner) {};

    BoloClientWorld.prototype.mapChanged = function(cell, oldType, hadMine, oldLife) {
      if (this.processingServerMessages) {
        return;
      }
      if (this.mapChanges[cell.idx] == null) {
        cell._net_oldType = oldType;
        cell._net_hadMine = hadMine;
        cell._net_oldLife = oldLife;
        this.mapChanges[cell.idx] = cell;
      }
    };

    BoloClientWorld.prototype.initChat = function() {
      this.chatMessages = $('<div/>', {
        id: 'chat-messages'
      }).appendTo(this.renderer.hud);
      this.chatContainer = $('<div/>', {
        id: 'chat-input'
      }).appendTo(this.renderer.hud).hide();
      return this.chatInput = $('<input/>', {
        type: 'text',
        name: 'chat',
        maxlength: 140
      }).appendTo(this.chatContainer).keydown((function(_this) {
        return function(e) {
          return _this.handleChatKeydown(e);
        };
      })(this));
    };

    BoloClientWorld.prototype.openChat = function(options) {
      options || (options = {});
      this.chatContainer.show();
      return this.chatInput.val('').focus().team = options.team;
    };

    BoloClientWorld.prototype.commitChat = function() {
      this.ws.send(JSON.stringify({
        command: this.chatInput.team ? 'teamMsg' : 'msg',
        text: this.chatInput.val()
      }));
      return this.closeChat();
    };

    BoloClientWorld.prototype.closeChat = function() {
      this.chatContainer.hide();
      return this.input.focus();
    };

    BoloClientWorld.prototype.receiveChat = function(who, text, options) {
      var element;
      options || (options = {});
      element = options.team ? $('<p/>', {
        "class": 'msg-team'
      }).text("<" + who.name + "> " + text) : $('<p/>', {
        "class": 'msg'
      }).text("<" + who.name + "> " + text);
      this.chatMessages.append(element);
      return window.setTimeout((function(_this) {
        return function() {
          return element.remove();
        };
      })(this), 7000);
    };

    BoloClientWorld.prototype.handleKeydown = function(e) {
      if (!(this.ws && this.player)) {
        return;
      }
      switch (e.which) {
        case 32:
          return this.ws.send(net.START_SHOOTING);
        case 37:
          return this.ws.send(net.START_TURNING_CCW);
        case 38:
          return this.ws.send(net.START_ACCELERATING);
        case 39:
          return this.ws.send(net.START_TURNING_CW);
        case 40:
          return this.ws.send(net.START_BRAKING);
        case 84:
          return this.openChat();
        case 82:
          return this.openChat({
            team: true
          });
      }
    };

    BoloClientWorld.prototype.handleKeyup = function(e) {
      if (!(this.ws && this.player)) {
        return;
      }
      switch (e.which) {
        case 32:
          return this.ws.send(net.STOP_SHOOTING);
        case 37:
          return this.ws.send(net.STOP_TURNING_CCW);
        case 38:
          return this.ws.send(net.STOP_ACCELERATING);
        case 39:
          return this.ws.send(net.STOP_TURNING_CW);
        case 40:
          return this.ws.send(net.STOP_BRAKING);
      }
    };

    BoloClientWorld.prototype.handleChatKeydown = function(e) {
      if (!(this.ws && this.player)) {
        return;
      }
      switch (e.which) {
        case 13:
          this.commitChat();
          break;
        case 27:
          this.closeChat();
          break;
        default:
          return;
      }
      return e.preventDefault();
    };

    BoloClientWorld.prototype.buildOrder = function(action, trees, cell) {
      if (!(this.ws && this.player)) {
        return;
      }
      trees || (trees = 0);
      return this.ws.send([net.BUILD_ORDER, action, trees, cell.x, cell.y].join(','));
    };

    BoloClientWorld.prototype.handleMessage = function(e) {
      var ate, command, data, error, i, len, length, message, pos, ref;
      error = null;
      if (e.data.charAt(0) === '{') {
        try {
          this.handleJsonCommand(JSON.parse(e.data));
        } catch (error1) {
          e = error1;
          error = e;
        }
      } else if (e.data.charAt(0) === '[') {
        try {
          ref = JSON.parse(e.data);
          for (i = 0, len = ref.length; i < len; i++) {
            message = ref[i];
            this.handleJsonCommand(message);
          }
        } catch (error1) {
          e = error1;
          error = e;
        }
      } else {
        this.netRestore();
        try {
          data = decodeBase64(e.data);
          pos = 0;
          length = data.length;
          this.processingServerMessages = true;
          while (pos < length) {
            command = data[pos++];
            ate = this.handleBinaryCommand(command, data, pos);
            pos += ate;
          }
          this.processingServerMessages = false;
          if (pos !== length) {
            error = new Error("Message length mismatch, processed " + pos + " out of " + length + " bytes");
          }
        } catch (error1) {
          e = error1;
          error = e;
        }
      }
      if (error) {
        this.failure('Connection lost (protocol error)');
        if (typeof console !== "undefined" && console !== null) {
          console.log("Following exception occurred while processing message:", e.data);
        }
        throw error;
      }
    };

    BoloClientWorld.prototype.handleBinaryCommand = function(command, data, offset) {
      var ascii, bytes, cell, code, idx, life, mine, owner, ref, ref1, ref2, ref3, ref4, ref5, ref6, ref7, sfx, tank_idx, x, y;
      switch (command) {
        case net.SYNC_MESSAGE:
          this.synchronized();
          return 0;
        case net.WELCOME_MESSAGE:
          ref = unpack('H', data, offset), (ref1 = ref[0], tank_idx = ref1[0]), bytes = ref[1];
          this.receiveWelcome(this.objects[tank_idx]);
          return bytes;
        case net.CREATE_MESSAGE:
          return this.netSpawn(data, offset);
        case net.DESTROY_MESSAGE:
          return this.netDestroy(data, offset);
        case net.MAPCHANGE_MESSAGE:
          ref2 = unpack('BBBBf', data, offset), (ref3 = ref2[0], x = ref3[0], y = ref3[1], code = ref3[2], life = ref3[3], mine = ref3[4]), bytes = ref2[1];
          ascii = String.fromCharCode(code);
          cell = this.map.cells[y][x];
          cell.setType(ascii, mine);
          cell.life = life;
          return bytes;
        case net.SOUNDEFFECT_MESSAGE:
          ref4 = unpack('BHHH', data, offset), (ref5 = ref4[0], sfx = ref5[0], x = ref5[1], y = ref5[2], owner = ref5[3]), bytes = ref4[1];
          this.renderer.playSound(sfx, x, y, this.objects[owner]);
          return bytes;
        case net.TINY_UPDATE_MESSAGE:
          ref6 = unpack('H', data, offset), (ref7 = ref6[0], idx = ref7[0]), bytes = ref6[1];
          bytes += this.netUpdate(this.objects[idx], data, offset + bytes);
          return bytes;
        case net.UPDATE_MESSAGE:
          return this.netTick(data, offset);
        default:
          throw new Error("Bad command '" + command + "' from server, at offset " + (offset - 1));
      }
    };

    BoloClientWorld.prototype.handleJsonCommand = function(data) {
      switch (data.command) {
        case 'nick':
          return this.objects[data.idx].name = data.nick;
        case 'msg':
          return this.receiveChat(this.objects[data.idx], data.text);
        case 'teamMsg':
          return this.receiveChat(this.objects[data.idx], data.text, {
            team: true
          });
        default:
          throw new Error("Bad JSON command '" + data.command + "' from server.");
      }
    };

    BoloClientWorld.prototype.rebuildMapObjects = function() {
      var i, len, obj, ref, ref1;
      this.map.pills = [];
      this.map.bases = [];
      ref = this.objects;
      for (i = 0, len = ref.length; i < len; i++) {
        obj = ref[i];
        if (obj instanceof WorldPillbox) {
          this.map.pills.push(obj);
        } else if (obj instanceof WorldBase) {
          this.map.bases.push(obj);
        } else {
          continue;
        }
        if ((ref1 = obj.cell) != null) {
          ref1.retile();
        }
      }
    };

    BoloClientWorld.prototype.netRestore = function() {
      var cell, idx, ref;
      BoloClientWorld.__super__.netRestore.apply(this, arguments);
      ref = this.mapChanges;
      for (idx in ref) {
        cell = ref[idx];
        cell.setType(cell._net_oldType, cell._net_hadMine);
        cell.life = cell._net_oldLife;
      }
      return this.mapChanges = {};
    };

    return BoloClientWorld;

  })(ClientWorld);

  helpers.extend(BoloClientWorld.prototype, require('./mixin'));

  allObjects.registerWithWorld(BoloClientWorld.prototype);

  module.exports = BoloClientWorld;

}).call(this);
