// Generated by CoffeeScript 1.12.7
(function() {
  var BoloObject, NetWorldObject,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  NetWorldObject = require('villain/world/net/object');

  BoloObject = (function(superClass) {
    extend(BoloObject, superClass);

    function BoloObject() {
      return BoloObject.__super__.constructor.apply(this, arguments);
    }

    BoloObject.prototype.styled = null;

    BoloObject.prototype.team = null;

    BoloObject.prototype.x = null;

    BoloObject.prototype.y = null;

    BoloObject.prototype.soundEffect = function(sfx) {
      return this.world.soundEffect(sfx, this.x, this.y, this);
    };

    BoloObject.prototype.getTile = function() {};

    return BoloObject;

  })(NetWorldObject);

  module.exports = BoloObject;

}).call(this);
