// Generated by CoffeeScript 1.12.7
(function() {
  var BoloWorldMixin;

  BoloWorldMixin = {
    boloInit: function() {
      return this.tanks = [];
    },
    addTank: function(tank) {
      tank.tank_idx = this.tanks.length;
      this.tanks.push(tank);
      if (this.authority) {
        return this.resolveMapObjectOwners();
      }
    },
    removeTank: function(tank) {
      var i, j, ref, ref1;
      this.tanks.splice(tank.tank_idx, 1);
      for (i = j = ref = tank.tank_idx, ref1 = this.tanks.length; ref <= ref1 ? j < ref1 : j > ref1; i = ref <= ref1 ? ++j : --j) {
        this.tanks[i].tank_idx = i;
      }
      if (this.authority) {
        return this.resolveMapObjectOwners();
      }
    },
    getAllMapObjects: function() {
      return this.map.pills.concat(this.map.bases);
    },
    spawnMapObjects: function() {
      var j, len, obj, ref;
      ref = this.getAllMapObjects();
      for (j = 0, len = ref.length; j < len; j++) {
        obj = ref[j];
        obj.world = this;
        this.insert(obj);
        obj.spawn();
        obj.anySpawn();
      }
    },
    resolveMapObjectOwners: function() {
      var j, len, obj, ref, ref1;
      ref = this.getAllMapObjects();
      for (j = 0, len = ref.length; j < len; j++) {
        obj = ref[j];
        obj.ref('owner', this.tanks[obj.owner_idx]);
        if ((ref1 = obj.cell) != null) {
          ref1.retile();
        }
      }
    }
  };

  module.exports = BoloWorldMixin;

}).call(this);
